### ISSUE TITLE
add ability to see current active profile

### ISSUE THREAD

**Issue by sultanmyrza** [aaronpowell/vscode-profile-switcher#22]

**Comment by nyikozoli** [comment]
You can easily achieve this with customizing the window title.

```yaml
  "profileSwitcher.storage": {
        "flutter": {
            "window.title": "Flutter profile${separator}${dirty}${activeEditorShort}${separator}${rootName}${separator}${appName}"
        },
        "csharp": {
            "window.title": "C# profile${separator}${dirty}${activeEditorShort}${separator}${rootName}${separator}${appName}",
            "[csharp]": {
                "editor.defaultFormatter": "ms-dotnettools.csharp"
            }
        }
    },
```
